### ISSUE TITLE
layers manager design - simple checkboxes

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#1017]

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/34486967-ee29d446-efda-11e7-96a6-f58d75ac7cc1.png)
![image](https://user-images.githubusercontent.com/26301386/34487009-0b610002-efdb-11e7-8abe-5907e3136e4c.png)

**Comment by idanbarak** [comment]
no need for search at the moment

**Comment by asafMasa** [comment]
@idanbarak @carmelorr as discussed with idan, we need to define specific functionality that will work "out" and "inside" in the same way.
I propose to unit it with #533 to define 8 layers in the "layers service" with hard coded identifiers and the check-boxes will be added by data in the layers service (diffrent for each env) - when we send link we will send "Layer_Identifier: checked/unchecked".

For annotations we can create a layer per case (and delete layer when we delete the case) - and then the annotation data will be saved in the "layers_service" instead of in the case"
Sharing url will send the annotation layer data in the link. (is that acceptable for security reasons?)

**Comment by carmelorr** [comment]
@asafMasa i don't understand you. lets talk in person about the annotations

**Comment by asafMasa** [comment]
@carmelorr do you want it as a check box or as "Show only favorites" toggle?
