### ISSUE TITLE
Enable an annotation with no fill

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#1151]

**Comment by carmelorr** [comment]
The user will be able to draw an annotation without fill or stroke by pressing the water drop icon.
the icon will have a tool tip saying "No fill" and "No stroke" accordingly.
Selecting a color will automatically de-active this button.
Pressing this button will remove the color (even if selected) from the square. the color selected will be saved so that the user will be able to easily activate the fill and stroke. 
Active button= opacity 100
Available button= opacity 80
In active button= opacity 40
 
![image](https://user-images.githubusercontent.com/26301386/36429526-9784fdb2-165b-11e8-8c1f-8004e51bb0ad.png)

**Comment by carmelorr** [comment]
https://biks.slack.com/files/U3YHTDU80/F9B8G5VU1/frame_84.svg
