### ISSUE TITLE
Add help section

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1253]

**Comment by asafMasa** [comment]
@idanbarak please talk with @ramtob about this issue when you are ready

**Comment by carmelorr** [comment]
The help section will include a carousel with images and text describing the different features. 
It will appear (be open) at startup as a default, but the user will be able to mark "don't show on startup".

**Comment by ramtob** [comment]
Hi @carmelorr @idanbarak 

The following is needed, in order to complete the development of the help drawer:

1. To complete the design, in general
2. Sending media, i.e. images. Also, they should be too big in volume.
3. There is also the issue of design adaptations for small screens. Content with images will be likely too big for small screen, at least with the images in their original sizes
4. The help drawer is supposed to open, by default, at app startup. But we also have a welcome notification, which also opens at application startup. So we have situations where there two collide.
(As I understood it, the help drawer opens at each session start, i.e. when opening the app in a new tab. And this continues unless the user marks the "don't show" checkbox)

**Comment by carmelorr** [comment]
![group 7](https://user-images.githubusercontent.com/26301386/40977128-c75e95dc-68d8-11e8-9e86-046a5d9dbfb2.png)
![group 7 1](https://user-images.githubusercontent.com/26301386/40977130-c8a550a2-68d8-11e8-81b4-cd27da2d53a2.png)
![group 7 2](https://user-images.githubusercontent.com/26301386/40977137-cb53610e-68d8-11e8-8548-65ba1e3667ee.png)
![group 7 3](https://user-images.githubusercontent.com/26301386/40977153-d366fc98-68d8-11e8-83ed-083ef0dda492.png)
![group 7 4](https://user-images.githubusercontent.com/26301386/40977159-d69edb38-68d8-11e8-96d7-f8d72023d938.png)
