### ISSUE TITLE
pixel range imagery (images without geo-registration/ reference)

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#272]
2 sub subjects:

1. how to indicate an un geo-registered image?
2. how to fix geo-registration?

**Comment by carmelorr** [comment]
2 sub subjects:

1. how to indicate an un geo-registered image?
2. how to fix geo-registration?

**Comment by carmelorr** [comment]
![5 8](https://user-images.githubusercontent.com/26301386/27538193-85c01a8c-5a7f-11e7-80c3-cb466757a9e6.png)
![5 9](https://user-images.githubusercontent.com/26301386/27538200-88fc8456-5a7f-11e7-8892-ecc20e6b3531.png)

**Comment by carmelorr** [comment]
border: 2px solid #E72828;

**Comment by idanbarak** [comment]
1. the design should also include the operations the user can make in order to fix the registration 
2. as i see it, the red border is not a viable solution because of the following:
- we use the border of the imagery panel in order to indicate the connection to timeline, what would be indicated if an overlay is active and has a false registration? two borders? too complicated..
- not indicative enough - the new audience for the app is the masses.. they dont even know what is an overlay with false registration. indication should much more literal.

i suggest with talk about this issue face to face and sort it out together

**Comment by carmelorr** [comment]
https://www.figma.com/file/OpHMLQ4eNnYWlv1lM0A2793w/Colombus-draft?node-id=171%3A429

**Comment by idanbarak** [comment]
@eldadcohen1 
I suggest to drop the "fix geo-registration" function - it  is too complicated for the masses

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/28366133-088a1640-6c94-11e7-96c3-b677538a7aed.png)
![image](https://user-images.githubusercontent.com/26301386/28366146-1d891316-6c94-11e7-90a0-b8d528af72c2.png)
