### ISSUE TITLE
As a <User>, I want to <to have a "Go-To" tool> so that <I can provide the coordinate of a specific location, navigate to it and see the details of the current location >

### ISSUE THREAD

**Issue by ronenru** [AnSyn/ansyn#350]

**Comment by carmelorr** [comment]
https://www.figma.com/file/OpHMLQ4eNnYWlv1lM0A2793w/Colombus-draft?node-id=253%3A0

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/28246877-33dab20a-6a2d-11e7-999a-0584bccd6936.png)

**Comment by carmelorr** [comment]
"Go-To" tool-

Insert coordinates (ED or WGS) will enable the user to go to this location by pressing the "Go button". If the user insert coordinates in ED the system will also show it in WGS, and vise versa.

The user can also choose to "pin location" in order to see the coordinates of a specific location (in ED and WGS). No icon is needed for this pin point.

**Comment by carmelorr** [comment]
@eldadcohen1 @idanbarak 
The customer site will need a "zone" section in the ED50

![image](https://user-images.githubusercontent.com/26301386/28259638-e39bc640-6adf-11e7-9ff7-f25d2a92d49e.png)

**Comment by idanbarak** [comment]
@carmelorr 
please add indication to coordinate on active imagery view

**Comment by carmelorr** [comment]
After pressing the "Go button", a cross marker will show the location in the active screen.

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/33241375-038d7a70-d2cd-11e7-94d7-8c01dcc9ae59.png)
