### ISSUE TITLE
Limit amount of overlays when lunching with context

### ISSUE THREAD

**Issue by yuvalbl** [AnSyn/ansyn#973]
**Area Context:**
- [ ] ask limit of x entities sorted by date (most recent first)

**Entity Context: (2 queries)**
- [ ] ask limit of x entities from start of time to entity date (most recent first)
- [ ] ask limit of x entities from entity date to now (oldest first)

**Comment by yuvalbl** [comment]
@asafMasa @carmelorr 
I cannot recall this issue, and the original message was edited.
please provide design for this matter

**Comment by carmelorr** [comment]
Area Context:#310

ask limit of 30 overlays sorted by date (most recent first)

Entity Context: (2 queries)#329

ask limit of 30 overlays from start of time to entity date (most recent first) 
ask limit of 30 overlays from entity date to now (oldest first)

**Comment by asafMasa** [comment]
Can't order by ascendind / descending date in planet - check with openaerial

**Comment by carmelorr** [comment]
@asafMasa @idanbarak 

Please mind that the entity context should have 30 overlays before and 30 overlays after- now we have only 35 overlays in total (most of them are after). Also as we discussed, the map should be in further zoom out- so the user will be able to see the whole polygon.

In area context- there are 33 overlays instead of 30.

**Comment by asafMasa** [comment]
@carmelorr as we discussed
planet is unaccurate. the real test will be with differant provider. (entity and area)

please send me the link you used in order to confirm your bug
